# Site settings
title: 'Yet Another Possibility'  # Your Title
tagline: '有约如铁'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: markdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
url: https://foreti.me/home

# Personal info
# codeurl: //github.com/zchen9/code/issues
fragmenturl: https://foreti.me/
avatar: ./images/logo.png
email: yanshisangc@@gmail.com
github: https://github.com/fakeyanss
twitter: https://twitter.com/fakeYanss
# spotify: https://open.spotify.com/user/lzmwuceujikwobk7ynydgsev1/
ins: https://foreti.me/gallery/

# Logo setting
logocolor: '#000'
