# Site settings
title: 'Nice Shot'  # Your Title
tagline: 'To find something interesting'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
codeurl: //github.com/zchen9/code/issues
fragmenturl: /fragment/

# Personal info
avatar: ./images/zchen9_spring.png
email: zhao.zchen9@gmail.com
github: https://github.com/zchen9
twitter: https://twitter.com/ch1oechao
spotify: https://open.spotify.com/user/lzmwuceujikwobk7ynydgsev1/
ins: https://www.instagram.com/ch1oechao/

# Logo setting
logocolor: '#000'
