# Site settings
title: 'F7ionsy' 
tagline: '爱你如斯'  
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: markdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
url: https://lihengdong.com/home

# Personal info
# codeurl: //github.com/zchen9/code/issues
fragmenturl: https://lihengdong.com/
avatar: ./images/logo.png
email: mailto:admin@lihengdong.com
github: https://github.com/F7ionsy
telegram: https://t.me/f7ionsy
qq: http://wpa.qq.com/msgrd?v=3&uin=1223981419&site=qq&menu=yes
twitter: https://twitter.com/fakeYanss
ins: https://foreti.me/gallery/
about: https://lihengdong.com/about/
todo: https://github.com/fakeYanss/Todo/issues
# spotify: https://open.spotify.com/user/lzmwuceujikwobk7ynydgsev1/

# Logo setting
logocolor: '#000'
